version: '3'
services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app
      - ~/.gitconfig:/etc/.gitconfig
    tty: true
    stdin_open: true
  db:
    image: mariadb:11.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bolog-db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:

